listendev/lstn

.github/workflows/release.yml, .github/workflows/tests.yml, .gitignore, .goreleaser.yml
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
Fixes #80 
Also:
- Fixes #81 
- Fixes #82 
- Fixes #84 
```bash
COSIGN_EXPERIMENTAL=1 cosign verify-blob --certificate artifact.pem --signature artifact.tar.gz.sig artifact.tar.gz
```
=> wip: release process

.goreleaser.yml, make/main.go, pkg/version/version.go, pkg/version/version_test.go
Also fixes the generation of the GitHub release URL.
Fixes #85 
Fixes #86
=> Fix the version in releases

.github/workflows/release.yml, .goreleaser.yml
=> Do not release against a shallow clone

.github/CONTRIBUTING.md
=> docs(.github): document the conventions we use for pull requests

reviewpad.yml
=> ci: enforce the pull request titles to follow the conventional commits spec

.github/workflows/build.yml, .github/workflows/tests.yml, reviewpad.yml
=> ci: create cross-build workflow

cmd/in/in.go, cmd/root/root.go, cmd/to/to.go, cmd/version/version.go, internal/project/project.go, internal/project/source.go, internal/project/source_test.go
=> chore: annotate commands with their source URLs

.gitignore, go.mod, go.sum, internal/docs/manpages.go, make/docs/main.go, make/main.go
Fixes #76 
Introduces `make/make man`
=> feat: manpages (docs) generator

.github/workflows/build.yml
=> ci: fix the cross-build workflow

.github/workflows/cla.yml, reviewpad.yml
=> ci: exclude dependabot from CLA

.github/workflows/release.yml, .goreleaser.yml
=> ci: sign without prompt + pin cosign-installer gh action

pkg/npm/packagelock.go, pkg/npm/packagelock_test.go
=> feat: ignore npm scripts

.gitattributes, .github/workflows/cla.yml, .github/workflows/lint.yml, .github/workflows/shellcheck.yml
=> ci: lint shell scripts

go.mod, go.sum, pkg/listen/context.go
=> feat: make request contexts have an ID

.github/workflows/lint.yml
I'm trying to solve the very frustrating linting outputs golangci-lint gives as they don't include a file name:line number one can refer to resolve issues.
=> chore: golangci-lint format print affected file

.github/workflows/build.yml, README.md, cmd/root/root.go
=> chore: fix automatic cheatsheet generation (no GITHUB_ACTIONS env var)

pkg/npm/types.go, pkg/npm/types_test.go
=> fix: parse package.json containing bundleDependencies correctly

cmd/commands_test.go, cmd/to/to.go
=> fix: make `lstn to --debug-options` work

pkg/cmd/report/templates/render.go, pkg/cmd/report/templates/testdata/container_with_verdicts_and_problems.md
=> fix: support again reporting org (@) NPM packages & do not assume certain metadata keys always exist

pkg/listen/listen.go, pkg/listen/options.go
=> feat: add WithUserAgent method

.github/workflows/release.yml
Bumping cosign as we are hitting
https://github.com/sigstore/cosign/issues/3614
=> ci: bump cosign

cmd/root/root.go, cmd/scan/scan.go, cmd/to/to.go
=> fix: make lstn to and lstn scan work again (NPM only for now)

.goreleaser.yml, cmd/ci/ci.go, make/main.go
=> feat: invoke argus (from PATH)

pkg/ci/env.go
=> fix: dump the SHA CI info field as GITHUB_SHA

pkg/ci/env.go, pkg/ci/env_test.go
=> fix: dump GitHub Actions variables with GITHUB_ prefix

pkg/reporter/factory/factory.go
=> feat(pkg/reporter): make the `pro` reporter work also on other GitHub actions events (not only `pull_request`)

cmd/ci/ci.go
=> refactor(cmd): port existing eavesdrop functionality to our new tool

.github/workflows/ci.yaml, .github/workflows/lint.yaml
=> ci: install the go version go.mod says
